/** Stable role codes persisted with administrator accounts. */
export const ADMIN_ROLES = [
  "owner",
  "manager",
  "catalog_editor",
  "order_operator",
  "content_editor",
  "viewer",
] as const;

export type AdminRole = (typeof ADMIN_ROLES)[number];

/** Action-level grants. Read permissions never imply access to sensitive fields. */
export const ADMIN_PERMISSIONS = [
  "dashboard:view",
  "analytics:read",
  "media:read",
  "media:create",
  "media:update",
  "media:delete",
  "categories:read",
  "categories:create",
  "categories:update",
  "categories:delete",
  "ingredients:read",
  "ingredients:create",
  "ingredients:update",
  "ingredients:delete",
  "dishes:read",
  "dishes:create",
  "dishes:update",
  "dishes:delete",
  "blogs:read",
  "blogs:create",
  "blogs:update",
  "blogs:publish",
  "blogs:delete",
  "seo:read",
  "seo:create",
  "seo:update",
  "seo:delete",
  "customers:read",
  "customers:read-sensitive",
  "customers:create",
  "customers:update",
  "customers:delete",
  "addresses:read-sensitive",
  "addresses:update",
  "addresses:delete",
  "admins:read",
  "admins:read-sensitive",
  "admins:create",
  "admins:update",
  "admins:assign-role",
  "admins:disable",
  "admins:delete",
  "orders:read",
  "orders:read-sensitive",
  "orders:create",
  "orders:update",
  "orders:cancel",
  "orders:export",
  "transactions:read",
  "transactions:read-sensitive",
  "transactions:create",
  "transactions:reconcile",
  "transactions:refund",
  "contacts:read",
  "contacts:read-sensitive",
  "contacts:delete",
  "logs:read",
  "settings:read",
  "settings:read-sensitive",
  "settings:update-content",
  "settings:update-operations",
  "settings:update-security",
] as const;

export type AdminPermission = (typeof ADMIN_PERMISSIONS)[number];

/** Complete, non-inheriting grants: changing a role cannot silently elevate another. */
export const ROLE_PERMISSIONS = {
  owner: ADMIN_PERMISSIONS,
  manager: [
    "dashboard:view",
    "analytics:read",
    "media:read",
    "media:create",
    "media:update",
    "media:delete",
    "categories:read",
    "categories:create",
    "categories:update",
    "categories:delete",
    "ingredients:read",
    "ingredients:create",
    "ingredients:update",
    "ingredients:delete",
    "dishes:read",
    "dishes:create",
    "dishes:update",
    "dishes:delete",
    "blogs:read",
    "blogs:create",
    "blogs:update",
    "blogs:publish",
    "blogs:delete",
    "seo:read",
    "seo:create",
    "seo:update",
    "seo:delete",
    "customers:read",
    "customers:read-sensitive",
    "customers:create",
    "customers:update",
    "addresses:read-sensitive",
    "addresses:update",
    "admins:read",
    "orders:read",
    "orders:read-sensitive",
    "orders:create",
    "orders:update",
    "orders:cancel",
    "orders:export",
    "transactions:read",
    "transactions:read-sensitive",
    "transactions:reconcile",
    "contacts:read",
    "contacts:read-sensitive",
    "contacts:delete",
    "logs:read",
    "settings:read",
    "settings:update-content",
    "settings:update-operations",
  ],
  catalog_editor: [
    "dashboard:view",
    "media:read",
    "media:create",
    "media:update",
    "media:delete",
    "categories:read",
    "categories:create",
    "categories:update",
    "categories:delete",
    "ingredients:read",
    "ingredients:create",
    "ingredients:update",
    "ingredients:delete",
    "dishes:read",
    "dishes:create",
    "dishes:update",
    "dishes:delete",
    "seo:read",
    "seo:create",
    "seo:update",
    "seo:delete",
  ],
  order_operator: [
    "dashboard:view",
    "customers:read",
    "customers:read-sensitive",
    "customers:update",
    "addresses:read-sensitive",
    "addresses:update",
    "orders:read",
    "orders:read-sensitive",
    "orders:create",
    "orders:update",
    "orders:cancel",
    "orders:export",
    "transactions:read",
    "transactions:read-sensitive",
    "transactions:reconcile",
    "contacts:read",
    "contacts:read-sensitive",
    "dishes:read",
  ],
  content_editor: [
    "dashboard:view",
    "media:read",
    "media:create",
    "media:update",
    "media:delete",
    "categories:read",
    "dishes:read",
    "blogs:read",
    "blogs:create",
    "blogs:update",
    "blogs:publish",
    "blogs:delete",
    "seo:read",
    "seo:create",
    "seo:update",
    "seo:delete",
    "settings:read",
    "settings:update-content",
  ],
  viewer: [
    "dashboard:view",
    "media:read",
    "categories:read",
    "ingredients:read",
    "dishes:read",
    "blogs:read",
    "seo:read",
    "settings:read",
  ],
} as const satisfies Record<AdminRole, readonly AdminPermission[]>;

export function isAdminRole(value: unknown): value is AdminRole {
  return typeof value === "string" && (ADMIN_ROLES as readonly string[]).includes(value);
}

export function permissionsForRole(role: unknown): readonly AdminPermission[] {
  return isAdminRole(role) ? ROLE_PERMISSIONS[role] : [];
}

export type AdminAccessActor = { role: unknown; active: boolean };

export function hasAdminPermission(actor: AdminAccessActor, permission: AdminPermission): boolean {
  return actor.active && permissionsForRole(actor.role).includes(permission);
}
