/**
 * Object storage boundary. Keys are opaque to callers and must be generated by the
 * media service, never from client filenames. Implementations must not expose a
 * provider SDK, credentials, or bucket policy to callers.
 */
export interface StorageObjectRef {
  readonly bucket: string;
  readonly key: string;
}

export interface StorageObjectInfo extends StorageObjectRef {
  readonly bytes: number;
  readonly contentType: string;
  readonly etag: string | null;
  readonly lastModified: Date;
}

export interface StorageUpload extends StorageObjectRef {
  /** The exact number of bytes expected; implementations reject a mismatch. */
  readonly contentLength: number;
  readonly contentType: string;
  readonly body: ReadableStream<Uint8Array>;
}

export interface StorageReadOptions {
  /** Inclusive, zero-based byte offset. Omit for the whole object. */
  readonly start?: number;
  /** Inclusive byte offset; requires start. */
  readonly end?: number;
}

export interface StorageReadResult {
  readonly body: ReadableStream<Uint8Array>;
  readonly bytes: number;
  readonly contentType: string;
  readonly totalBytes: number;
}

export interface StorageSignedReadUrl {
  readonly url: string;
  readonly expiresAt: Date;
}

export interface StorageHealth {
  readonly healthy: boolean;
  readonly checkedAt: Date;
  /** Stable diagnostic code only; never credentials, endpoints, or raw SDK errors. */
  readonly reason: "ok" | "unreachable" | "unauthorized" | "bucket_missing" | "unknown";
}

export type StorageErrorCode =
  | "invalid_input"
  | "not_found"
  | "already_exists"
  | "length_mismatch"
  | "unavailable"
  | "unauthorized";

export class StorageError extends Error {
  constructor(readonly code: StorageErrorCode) {
    super(code);
    this.name = "StorageError";
  }
}

export interface StorageProvider {
  /** Create only: an existing destination must fail, never overwrite. */
  upload(input: StorageUpload): Promise<StorageObjectInfo>;
  /** Return null for a missing object; other failures throw a sanitized StorageError. */
  stat(ref: StorageObjectRef): Promise<StorageObjectInfo | null>;
  /** Stream content; implementations must honor inclusive range bounds. */
  read(ref: StorageObjectRef, options?: StorageReadOptions): Promise<StorageReadResult>;
  /** Signed GET only. Expiry is in whole seconds, 1–900. */
  signedReadUrl(ref: StorageObjectRef, expiresInSeconds: number): Promise<StorageSignedReadUrl>;
  /** Idempotent: deleting an absent object succeeds. */
  delete(ref: StorageObjectRef): Promise<void>;
  /** Create-only destination; source remains. */
  copy(source: StorageObjectRef, destination: StorageObjectRef): Promise<StorageObjectInfo>;
  /** Copy then delete; not atomic across objects. See docs for recovery. */
  move(source: StorageObjectRef, destination: StorageObjectRef): Promise<StorageObjectInfo>;
  /** Check storage reachability and the configured bucket, without exposing secrets. */
  health(): Promise<StorageHealth>;
}
